name: "publish"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  check:
    uses: "./.github/workflows/check.yml"

  publish:
    runs-on: "ubuntu-latest"
    needs:
      - "check"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          ref: "js"

      - name: "Remove everything."
        run: |
          rm -rf *

      - name: "Create worktree from `master` branch."
        run: |
          git fetch --all
          git worktree add worktree-master master

      - name: "Build worktree."
        run: |
          cd worktree-master
          npm ci
          npm run build

      - name: "Move built files."
        run: |
          mv -v worktree-master/build/* .

      - name: "Move `package.json`."
        run: |
          mv -v 'worktree-master/package.json' .

      - name: "Cleanup `package.json`."
        run: |
          set -x -e -u -o pipefail

          node -p -e 'Object.keys(require("./package.json")).join("\n")' \
          | grep -vE '^(name|version|private)$' \
          | sed -r 's@^@npm pkg delete @g' \
          | sh

      - name: "Remove worktree."
        run: |
          git worktree remove -f worktree-master

      - name: "`git config`"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: "Commit and push"
        run: |
          git add --all -v

          # Abort if there's no changed files.
          git diff --cached --quiet && exit 0

          git commit -m 'Update'
          git push -u origin js
