name: "pull_request"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "ready_for_review"
      - "review_requested"

jobs:
  check:
    uses: "./.github/workflows/check.yml"
